name: EasyGamemode
description: Easy to use plugin that changes your gamemode
website: https://www.github.com/ErosionYT
main: ErosionYT\EasyGM\Main
author: ErosionYT
version: 2.0.1
api: 4.0.0

permissions:
  easygamemode.command.gmc:
    default: op
  easygamemode.command.gms:
    default: op
  easygamemode.command.gmspc:
    default: op
  easygamemode.command.gma:
    default: op
  easygamemode.command.ui:
    default: op

